import Link from "next/link";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <nav style={{ padding: "5px 0" }}>
            <Link href="/test">test</Link>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
